### ISSUE TITLE
Sass partial should start with underscore

### ISSUE THREAD

**Issue by jonaswindey** [linxtion/react-image-gallery#1]
I'm using sass-loader 1.x (webpack) and get the following error:

```
ERROR in ./~/css-loader!./~/sass-loader!./app/style/style.scss
Module build failed: 
@import "../node_modules/react-image-gallery/src/ImageGallery.scss";
       ^
      File to import not found or unreadable: ../node_modules/react-image-gallery/src/_ImageGallery.scss
```

According to the specs, sass @imports should start with an underscore, so I would suggest you rename ImageGallery.scss to _ImageGallery.scss since it's a partial.

**Comment by linxtion** [comment]
Its weird that sass-loader tries to assume a partial. Partials don't really have anything to do with imports, they're used to distinguished if it should be generated into a css file or not.
