### ISSUE TITLE
React 0.14.0 warning

### ISSUE THREAD

**Issue by bobiblazeski** [linxtion/react-image-gallery#15]
Since I switched to React v0.14.0 I get fallowing warnings:

Warning: ImageGallery.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.warning @ main.js:2231
main.js:2231 Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `ImageGallery`.

**Comment by linxtion** [comment]
@bobiblazeski fixed with version 0.4.5 of react-image-gallery

**Comment by bobiblazeski** [comment]
Warning is gone, many thanks.
