### ISSUE TITLE
Cannot find module 'react/addons'

### ISSUE THREAD

**Issue by jonaswindey** [linxtion/react-image-gallery#2]
When I 
```var ImageGallery = require('react-image-gallery');```
I get: Cannot find module 'react/addons'

I have to require the whole src path like this:
```var ImageGallery = require('react-image-gallery/src/ImageGallery.react.jsx');``` 
To get it to work.

**Comment by linxtion** [comment]
Thats odd, what version of react are you using? I will try to replicate it.

**Comment by edoloughlin** [comment]
I'm seeing this with react-0.13.3.

**Comment by linxtion** [comment]
Thanks, I will look into it, along with other fixes I plan to release later this week.

**Comment by linxtion** [comment]
I can't seem to replicate this. I've tried installing react-0.13.3 and react-image-gallery on a fresh build and it worked fine. Can you replicate this using a new build (just react + react-image-gallery)?

**Comment by rblakeley** [comment]
getting the same error with react-0.12.1

**Comment by linxtion** [comment]
That is a warning, and related to webpack it seems. If you like feel free to open a PR for a fix.

**Comment by rblakeley** [comment]
The second part was just supplemental info for the primary issue, this warning:
```
Cannot find module 'react/addons'
```

It's an error that is causing failure with the Gallery.

**Comment by linxtion** [comment]
@rblakeley I've remove `react/addons` from the build and released 0.4.2.

**Comment by rblakeley** [comment]
@linxtion cheers
