### ISSUE TITLE
npm package broken

### ISSUE THREAD

**Issue by aflanagan** [linxtion/react-image-gallery#21]
I believe the 0.4.9 and 0.5.0 releases are broken because your package.json `main` key points to `./build/image-gallery` which was removed when you bumped to 0.4.9

**Comment by linxtion** [comment]
please use 0.5.0, 0.4.9 is broken.

**Comment by linxtion** [comment]
I added .npmignore in `v0.5.0` so the build files will be included.

**Comment by linxtion** [comment]
I've also unpublished `v0.4.9` as it is completely broken

**Comment by aflanagan** [comment]
Got it. Fwiw, if you had bumped to 0.4.10 instead of rolling to 0.5.0 it
would have allowed anyone who was allowing bumps on the point release to
automatically update.

**Comment by linxtion** [comment]
That's very true. Totally did a panic count :)
