### ISSUE TITLE
Could you please check this issue?

### ISSUE THREAD

**Issue by cynthia-pm** [linxtion/react-image-gallery#23]
Warning: ReactDOMComponent: Do not access .props of a DOM node; instead, recreate the props as `render` did originally or read the DOM properties/attributes directly from this node (e.g., this.refs.box.className). This DOM node was rendered by `ImageGallery`.

**Comment by linxtion** [comment]
This issue is caused by #18, I'll look into it.

**Comment by cynthia-pm** [comment]
Could you try to change t to let totalThumbnails = thumbNode.children.length; ?

**Comment by linxtion** [comment]
That would solve it, but it would break #18 again, so I'm looking into a way so both can work.

**Comment by linxtion** [comment]
Alright, so it seems I can't support both versions. I will apply what you mentioned, and the warning message should go away.

**Comment by linxtion** [comment]
0.5.1 fixes the issue. Thanks for reporting it.

**Comment by cynthia-pm** [comment]
Thanks
