### ISSUE TITLE
Opacity-based transitions doesn't work when lazyLoad=true

### ISSUE THREAD

**Issue by msn0** [linxtion/react-image-gallery#24]
Switching between nonadjacent images is not smooth. Transitions based on opacity doesn't work because(?) elements are re-rendered thus removed and placed once again in the DOM. Consider ReactCSSTransitionGroup or @keyframes as a solution.

**Comment by linxtion** [comment]
I will take a look at this, sometime this week.

**Comment by linxtion** [comment]
@msn0 this is now fixed in v0.5.3
