### ISSUE TITLE
Can I handle Clicks

### ISSUE THREAD

**Issue by frostymarvelous** [linxtion/react-image-gallery#25]
I need to open links when image or description is clicked.
Is there anyway to do this?

**Comment by linxtion** [comment]
I will be adding a way to add `href` to each slide so that it is clickable. Will update you once I release it.

**Comment by frostymarvelous** [comment]
Great. but one thing. If you use hrefs, that limits some of us.
eg, I use React-Router which uses Link components to use the HTML5 history api.

Do you think you could, 

1. give us a click callback
2. allow us to prove the markup, it could be an image or an image wrapped in an href.

more flexibility to enable us to do more stuff with it.
Thanks.

**Comment by linxtion** [comment]
I see what you mean, let me think about it a bit. Thanks.

**Comment by linxtion** [comment]
@frostymarvelous I've released `v0.5.3` which will allow you to provide a `onClick` function prop to `ImageGallery`. This should solve your issue with opening links when an image is clicked.

I don't think allowing custom html injected slides is a good idea at this moment, but I'm open to suggestions if have a clean solution.

**Comment by frostymarvelous** [comment]
Great! I was really waiting for this.
Have a feature to deliver by tomorrow morning.

I will try to do something when I have some time.
