### ISSUE TITLE
Add swipe support

### ISSUE THREAD

**Issue by abhilashsajeev** [linxtion/react-image-gallery#3]
It will be great if the thumbnails section have a smoother swipe support.

**Comment by linxtion** [comment]
I plan to add swipe support for the slides soon.

**Comment by abhilashsajeev** [comment]
Cool. I am looking forward to it.

**Comment by linxtion** [comment]
@abhilashsajeev release 0.4.1 adds simple swipe support for the Slides.

**Comment by abhilashsajeev** [comment]
Yeah. I see that. Thanks @linxtion
